name: Test building commits

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            meson ninja-build valac \
            libgtk-4-dev libadwaita-1-dev \
            libgranite-7-dev libgee-0.8-dev \
            libglib2.0-dev dbus-x11 libvala-0.56-dev\
            libjson-glib-dev libjson-glib-1.0-0 \
            gettext libgtksourceview-5-0 libgtksourceview-5-dev \
            desktop-file-utils appstream dbus-x11

      - name: Configure and Build Folio
        run: |
          meson setup builddir --prefix=/usr
          meson compile -C builddir

      - name: Run Tests
        env:
          GIO_USE_VFS: local
        run: |
          dbus-run-session -- meson test -C builddir --no-suite blueprint-compiler
